# Generated by Django 4.0.4 on 2022-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Currency', models.CharField(max_length=3)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('TransactionDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
